<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" >
    <xacro:include filename="$(find demo_description)/urdf/fishbot/common_inertia.xacro"/>

    <xacro:macro name="base_link" params="length radius">
        <link name="base_footprint"/>
            
        <!-- 机器人的身体部分 -->
        <link name="base_link">
            <!--部件外观描述-->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转量 -->
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <!-- 几何形状 -->
                <geometry>
                <!-- 圆柱体 半径 长度 -->
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <!-- 材质颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <!-- 碰撞描述 -->
            <collision>
                <!-- 沿着自己几何中心的偏移和旋转量 -->
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <!-- 几何形状 -->
                <geometry>
                <!-- 圆柱体 半径 长度 -->
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <!-- 材质颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <!-- 惯性描述 -->
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>

        <!-- 机器人的关节,用于组成 -->
        <joint name="base_link_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 ${length/2+wheel_radius-0.001}" rpy="0 0 0"/>
        </joint>

    </xacro:macro>
</robot>