<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="fishbot">
    <xacro:include filename="$(find demo_description)/urdf/fishbot/common_inertia.xacro"/>
    <!-- 机器人底盘的参数 -->
    <xacro:property name="base_length" value="0.12"/>
    <xacro:property name="base_radius" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.032"/>

    <!--基础部分 base_link-->
    <xacro:include filename="$(find demo_description)/urdf/fishbot/base.urdf.xacro"/>
    <!--传感器部分-->
    <xacro:include filename="$(find demo_description)/urdf/fishbot/sensor/imu.urdf.xacro"/>
    <xacro:include filename="$(find demo_description)/urdf/fishbot/sensor/laser.urdf.xacro"/>
    <xacro:include filename="$(find demo_description)/urdf/fishbot/sensor/camera.urdf.xacro"/>
    <!--执行器部分-->
    <xacro:include filename="$(find demo_description)/urdf/fishbot/actuator/wheel.urdf.xacro"/>
    <xacro:include filename="$(find demo_description)/urdf/fishbot/actuator/caster.urdf.xacro"/>

    <xacro:base_link length="${base_length}" radius="${base_radius}"/>
    <xacro:imu_link xyz="0 0 0.02"/>
    <xacro:camera_link xyz="${base_radius} 0 0.075"/>
    <xacro:laser_link xyz="0.0 0 0.10"/>

    <xacro:wheel_xacro wheel_name="left_wheel" xyz="0.0 0.1 -${base_length/2}"/>
    <xacro:wheel_xacro wheel_name="right_wheel" xyz="0.0 -0.1 -${base_length/2}"/>
    <xacro:caster_xacro caster_name="front_caster" xyz="0.08 0.0 -${base_length/2+wheel_radius/2}"/>
    <xacro:caster_xacro caster_name="back_caster" xyz="-0.08 0.0 -${base_length/2+wheel_radius/2}"/>


</robot>
